name: Perform checks

on:
  merge_group:
  pull_request_target:
    branches: ['main']
    types: ['opened', 'reopened', 'synchronize']

jobs:
  perform-checks:
    name: Run checks
    runs-on: ubuntu-latest
    steps:
      - id: perform-checks
        name: Run checks
        uses: nedix/actions/perform-checks@main
        with:
          command: echo 'Check'
